set(_CATKIN_CURRENT_PACKAGE "ebot_mani")
set(ebot_mani_VERSION "0.3.0")
set(ebot_mani_MAINTAINER "naman <namanmalik0210@gmail.com>")
set(ebot_mani_PACKAGE_FORMAT "1")
set(ebot_mani_BUILD_DEPENDS "rospy" "std_msgs" "geometry_msgs" "ros_tcp_endpoint" "moveit_msgs" "sensor_msgs" "controller_manager" "roslaunch" "message_generation")
set(ebot_mani_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "geometry_msgs" "ros_tcp_endpoint" "message_runtime" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "xacro" "topic_tools" "moveit_msgs" "sensor_msgs" "controller_manager" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "tf2_ros" "xacro" "ebot_description")
set(ebot_mani_BUILDTOOL_DEPENDS "catkin")
set(ebot_mani_BUILDTOOL_EXPORT_DEPENDS )
set(ebot_mani_EXEC_DEPENDS "rospy" "std_msgs" "geometry_msgs" "ros_tcp_endpoint" "message_runtime" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "xacro" "topic_tools" "moveit_msgs" "sensor_msgs" "controller_manager" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "tf2_ros" "xacro" "ebot_description")
set(ebot_mani_RUN_DEPENDS "rospy" "std_msgs" "geometry_msgs" "ros_tcp_endpoint" "message_runtime" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "xacro" "topic_tools" "moveit_msgs" "sensor_msgs" "controller_manager" "moveit_setup_assistant" "tf2_ros" "ebot_description")
set(ebot_mani_TEST_DEPENDS )
set(ebot_mani_DOC_DEPENDS )
set(ebot_mani_URL_WEBSITE "http://moveit.ros.org/")
set(ebot_mani_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(ebot_mani_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(ebot_mani_DEPRECATED "")